"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export type LiveStore={id:string;tenant_id:string;name:string;public_slug:string;accepting_orders:boolean;is_storefront_published:boolean;accepts_delivery:boolean;accepts_pickup:boolean;default_prep_minutes:number};
export type LiveProduct={id:string;name:string;description:string|null;category_id:string;base_price:number;is_available:boolean};
export type LiveOrder={id:string;display_number:number;customer_name:string;status:string;total_amount:number;created_at:string;fulfillment_type:string;order_items:{id:string;product_name:string;quantity:number;notes:string|null}[]};
export const statusNames:Record<string,string>={new:"Novo",confirmed:"Confirmado",preparing:"Em preparo",ready:"Pronto",awaiting_driver:"Aguardando entregador",out_for_delivery:"Saiu para entrega",delivered:"Entregue",canceled:"Cancelado"};
const next:Record<string,string[]>={new:["confirmed","canceled"],confirmed:["preparing","canceled"],preparing:["ready","canceled"],ready:["awaiting_driver","out_for_delivery","delivered","canceled"],awaiting_driver:["out_for_delivery","canceled"],out_for_delivery:["delivered","canceled"]};
const field="w-full rounded-xl border border-stone-300 bg-white px-3 py-2.5 text-sm";
const button="rounded-xl bg-[#202823] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50";
const money=(v:number)=>Number(v).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export function LiveOperations({store,products,categories,orders,zones}:{store:LiveStore;products:LiveProduct[];categories:{id:string;name:string}[];orders:LiveOrder[];zones:{id:string;name:string;delivery_fee:number;minimum_order_amount:number}[]}) {
 const router=useRouter();const [tab,setTab]=useState("Pedidos");const [feedback,setFeedback]=useState("");const [busy,setBusy]=useState(false);const [edit,setEdit]=useState<LiveProduct|null>(null);const [query,setQuery]=useState("");
 useEffect(()=>{const client=createClient();if(!client)return;const ch=client.channel(`orders-${store.id}`).on("postgres_changes",{event:"*",schema:"public",table:"orders",filter:`store_id=eq.${store.id}`},()=>router.refresh()).subscribe();const poll=window.setInterval(()=>router.refresh(),15000);return()=>{clearInterval(poll);void client.removeChannel(ch);};},[store.id,router]);
 async function save(input:Record<string,unknown>){setBusy(true);setFeedback("");try{const response=await fetch(`/api/stores/${store.id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});const result=await response.json() as {error?:string};if(!response.ok)throw Error(result.error);setFeedback("Salvo com sucesso.");router.refresh();return true;}catch(e){setFeedback(e instanceof Error?e.message:"Falha ao salvar.");return false;}finally{setBusy(false);}}
 async function form(event:React.FormEvent<HTMLFormElement>,action:string){event.preventDefault();const target=event.currentTarget;const f=new FormData(target);const value=Object.fromEntries(f.entries());let payload:Record<string,unknown>={action,...value};if(action==="product")payload={...payload,base_price:Number(value.base_price),is_available:f.has("is_available"),...(edit?{id:edit.id}:{})};if(action==="zone")payload={...payload,delivery_fee:Number(value.delivery_fee),minimum_order_amount:Number(value.minimum_order_amount)};if(action==="settings")payload={action,accepting_orders:f.has("accepting_orders"),is_storefront_published:f.has("is_storefront_published"),accepts_delivery:f.has("accepts_delivery"),accepts_pickup:f.has("accepts_pickup"),default_prep_minutes:Number(value.default_prep_minutes)};if(await save(payload)){if(action!=="settings")target.reset();if(action==="product")setEdit(null);}}
 const active=orders.filter(o=>!["delivered","canceled"].includes(o.status));
 return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-stone-500">Painel do estabelecimento</p><h1 className="mt-1 text-3xl font-semibold">{store.name}</h1></div><Link href={`/loja/${store.public_slug}`} className="rounded-xl border bg-white px-4 py-3 text-sm font-semibold">Ver loja</Link></div><nav className="flex gap-2 overflow-x-auto border-b pb-3" aria-label="Operação">{["Pedidos","Cozinha","Cardápio","Entrega","Configurações"].map(t=><button key={t} onClick={()=>setTab(t)} className={`shrink-0 rounded-xl px-4 py-3 text-sm font-semibold ${tab===t?"bg-[#202823] text-white":"bg-white"}`}>{t}</button>)}</nav>{feedback&&<p role="status" className="rounded-xl border bg-white p-4 text-sm">{feedback}</p>}
 {(tab==="Pedidos"||tab==="Cozinha")&&<><div className="grid grid-cols-2 gap-4"><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-stone-500">Em operação</p><strong className="mt-2 block text-3xl">{active.length}</strong></div><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-stone-500">Vendas exibidas, sem cancelados</p><strong className="mt-2 block text-3xl">{money(orders.filter(o=>o.status!=="canceled").reduce((n,o)=>n+Number(o.total_amount),0))}</strong></div></div><p className="text-sm text-stone-500">Últimos 100 pedidos · atualização automática</p><div className="grid gap-4 lg:grid-cols-2">{(tab==="Cozinha"?active.filter(o=>["new","confirmed","preparing"].includes(o.status)):orders).map(order=><article key={order.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><h2 className="font-bold">#{order.display_number} · {order.customer_name}</h2><span className="text-sm font-semibold text-orange-800">{statusNames[order.status]}</span></div><p className="mt-2 text-sm text-stone-500">{new Date(order.created_at).toLocaleString("pt-BR")} · {order.fulfillment_type==="delivery"?"Entrega":order.fulfillment_type==="pickup"?"Retirada":"No local"}</p><ul className="my-4 space-y-2">{order.order_items.map(item=><li key={item.id}><span className="font-semibold">{item.quantity}× {item.product_name}</span>{item.notes&&<p className="text-sm text-orange-800">{item.notes}</p>}</li>)}</ul><strong>{money(order.total_amount)}</strong><div className="mt-4 flex flex-wrap gap-2">{(next[order.status]??[]).map(status=><button disabled={busy} key={status} className={button} onClick={()=>void save({action:"order",id:order.id,status})}>{statusNames[status]}</button>)}</div></article>)}</div>{!active.length&&<p className="rounded-xl border border-dashed p-8 text-center text-stone-500">Nenhum pedido em produção.</p>}</>}
 {tab==="Cardápio"&&<div className="grid items-start gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-4"><input aria-label="Buscar produtos" placeholder="Buscar produto" value={query} onChange={e=>setQuery(e.target.value)} className={field}/>{products.filter(p=>p.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())).map(p=><article key={p.id} className="flex items-center justify-between gap-3 rounded-xl border bg-white p-4"><div><h2 className="font-semibold">{p.name}</h2><p className="text-sm text-stone-500">{money(p.base_price)} · {p.is_available?"Disponível":"Pausado"}</p></div><div className="flex gap-2"><button onClick={()=>setEdit(p)} className="rounded-lg border px-3 py-2 text-sm">Editar</button><button disabled={busy} onClick={()=>void save({action:"availability",id:p.id,is_available:!p.is_available})} className="rounded-lg border px-3 py-2 text-sm">{p.is_available?"Pausar":"Ativar"}</button></div></article>)}{!products.length&&<p className="p-6 text-stone-500">Crie uma categoria e adicione seu primeiro produto.</p>}</div><div className="space-y-5"><form className="space-y-3 rounded-2xl border bg-white p-5" onSubmit={e=>void form(e,"category")}><h2 className="font-semibold">Nova categoria</h2><label className="block text-sm">Nome<input name="name" required maxLength={120} className={field}/></label><button disabled={busy} className={button}>Criar categoria</button></form><form key={edit?.id??"new"} className="space-y-3 rounded-2xl border bg-white p-5" onSubmit={e=>void form(e,"product")}><h2 className="font-semibold">{edit?"Editar produto":"Novo produto"}</h2><label className="block text-sm">Nome<input name="name" required defaultValue={edit?.name} className={field}/></label><label className="block text-sm">Descrição<textarea name="description" defaultValue={edit?.description??""} className={field}/></label><label className="block text-sm">Categoria<select name="category_id" required defaultValue={edit?.category_id??""} className={field}><option value="" disabled>Selecione</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="block text-sm">Preço (R$)<input name="base_price" type="number" min="0" step="0.01" required defaultValue={edit?.base_price} className={field}/></label><label className="flex gap-2 text-sm"><input type="checkbox" name="is_available" defaultChecked={edit?.is_available??true}/>Disponível</label><button disabled={busy||!categories.length} className={button}>Salvar produto</button>{edit&&<button type="button" className="ml-3 text-sm underline" onClick={()=>setEdit(null)}>Cancelar</button>}</form></div></div>}
 {tab==="Entrega"&&<div className="grid gap-5 md:grid-cols-2"><div className="space-y-3">{zones.map(z=><article key={z.id} className="rounded-xl border bg-white p-5"><h2 className="font-semibold">{z.name}</h2><p className="mt-2">Entrega {money(z.delivery_fee)} · mínimo {money(z.minimum_order_amount)}</p></article>)}{!zones.length&&<p>Nenhum bairro cadastrado.</p>}</div><form onSubmit={e=>void form(e,"zone")} className="space-y-4 rounded-2xl border bg-white p-5"><h2 className="font-semibold">Adicionar bairro</h2><label className="block text-sm">Bairro<input className={field} name="name" required/></label><label className="block text-sm">Taxa (R$)<input className={field} type="number" min="0" step="0.01" name="delivery_fee" required/></label><label className="block text-sm">Pedido mínimo (R$)<input className={field} type="number" min="0" step="0.01" name="minimum_order_amount" defaultValue="0" required/></label><button disabled={busy} className={button}>Salvar bairro</button></form></div>}
 {tab==="Configurações"&&<form onSubmit={e=>void form(e,"settings")} className="max-w-xl space-y-5 rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Publicação e atendimento</h2>{([["is_storefront_published","Publicar cardápio",store.is_storefront_published],["accepting_orders","Receber novos pedidos",store.accepting_orders],["accepts_delivery","Oferecer delivery",store.accepts_delivery],["accepts_pickup","Oferecer retirada",store.accepts_pickup]] as const).map(([name,label,checked])=><label key={name} className="flex items-center gap-3"><input name={name} type="checkbox" defaultChecked={checked}/>{label}</label>)}<label className="block text-sm">Prazo de preparo (minutos)<input name="default_prep_minutes" type="number" required min="1" max="240" defaultValue={store.default_prep_minutes} className={field}/></label><button disabled={busy} className={button}>Salvar configurações</button></form>}
 </div>;
}
