"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
export function LiveOnboarding(){
 const router=useRouter();const [name,setName]=useState("");const [slug,setSlug]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/onboarding",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tenantName:name,tenantSlug:slug,storeName:name,storeSlug:slug})});const result=await response.json() as {error?:string;onboarding?:{created_store_id:string}[]};if(!response.ok||!result.onboarding?.[0])throw Error(result.error??"Não foi possível criar a loja");router.push(`/painel/${result.onboarding[0].created_store_id}`);}catch(e){setError(e instanceof Error?e.message:"Falha na conexão");}finally{setBusy(false);}}
 return <main className="grid min-h-screen place-items-center bg-stone-50 p-5"><form onSubmit={submit} className="w-full max-w-lg space-y-5 rounded-2xl border bg-white p-8"><Link href="/acesso" className="text-sm underline">Voltar</Link><h1 className="text-3xl font-semibold">Crie seu estabelecimento</h1><p className="text-stone-600">Você será o proprietário. A loja fica privada até você publicar o cardápio.</p><label className="block text-sm font-semibold">Nome<input className="mt-2 w-full rounded-xl border p-3" required minLength={2} maxLength={140} value={name} onChange={e=>{setName(e.target.value);if(!slug)setSlug(e.target.value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""));}}/></label><label className="block text-sm font-semibold">Link da loja<input className="mt-2 w-full rounded-xl border p-3" required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={80} value={slug} onChange={e=>setSlug(e.target.value)}/><span className="mt-2 block text-xs text-stone-500">/loja/{slug||"seu-estabelecimento"}</span></label>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-[#202823] p-3 font-semibold text-white disabled:opacity-50">{busy?"Criando…":"Criar estabelecimento"}</button></form></main>;
}
